[package]
name = "nemo-lsp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nemo-frontend = { path = "../nemo-frontend" }
lsp-server = "0.7.4"
lsp-types = "=0.94"
log = "0.4.17"
serde_json = "1.0.96"
serde = { version = "1.0.156", features = ["derive"] }
crossbeam-channel = "0.5.6"
